@php($message = urlencode("Hola, me interesa la propiedad: {$property->title}. Me gustaría recibir más información. ".request()->url()))
<x-public-layout title="{{ $property->title }} | Grupo Mundo Patrimonial" description="{{ $property->short_description ?: Str::limit(strip_tags($property->description), 150) }}">
    <section class="mx-auto grid max-w-7xl gap-10 px-5 py-12 lg:grid-cols-[1.1fr_.9fr] lg:px-8">
        <div><img src="{{ $property->cover_url }}" alt="{{ $property->title }}" class="aspect-[4/3] w-full rounded-3xl object-cover shadow"><div class="mt-4 grid grid-cols-4 gap-3">@foreach($property->images->take(4) as $image)<img src="{{ asset('storage/'.$image->path) }}" alt="{{ $image->alt_text ?: $property->title }}" class="aspect-square rounded-xl object-cover">@endforeach</div></div>
        <div><p class="font-extrabold text-[#c59d47]">{{ $property->operation_type->label() }} · {{ $property->property_type }}</p><h1 class="mt-3 text-4xl font-black text-[#082142]">{{ $property->title }}</h1><p class="mt-4 text-3xl font-black text-[#082142]">{{ '$'.number_format($property->price, 0) }} {{ $property->currency }}{{ $property->operation_type->value === 'rent' ? ' / '.($property->rent_period ?: 'mes') : '' }}</p><p class="mt-4 text-slate-600">{{ $property->street }} {{ $property->exterior_number }}, {{ $property->neighborhood }}, {{ $property->city }}, {{ $property->state }}</p>
            <div class="mt-6 grid grid-cols-2 gap-3 text-sm"><span>Recámaras: {{ $property->bedrooms ?? 'N/D' }}</span><span>Baños: {{ $property->bathrooms ?? 'N/D' }}</span><span>Estacionamientos: {{ $property->parking_spaces ?? 'N/D' }}</span><span>Construcción: {{ $property->construction_area ?? 'N/D' }} m²</span><span>Terreno: {{ $property->land_area ?? 'N/D' }} m²</span><span>Antigüedad: {{ $property->age ?? 'N/D' }}</span></div>
            <a href="https://wa.me/{{ config('company.whatsapp_number') }}?text={{ $message }}" class="mt-8 inline-flex rounded-full bg-[#d3aa56] px-7 py-4 font-extrabold text-[#082142]">Solicitar por WhatsApp</a>
        </div>
    </section>
    <section class="mx-auto grid max-w-7xl gap-10 px-5 pb-16 lg:grid-cols-[1fr_380px] lg:px-8">
        <div><h2 class="text-2xl font-black text-[#082142]">Descripción</h2><p class="mt-4 whitespace-pre-line leading-8">{{ $property->description }}</p><h2 class="mt-10 text-2xl font-black text-[#082142]">Amenidades</h2><div class="mt-4 flex flex-wrap gap-3">@forelse($property->amenities as $amenity)<span class="rounded-full bg-[#f4ead5] px-4 py-2 text-sm font-bold text-[#082142]">{{ $amenity->name }}</span>@empty<span class="text-slate-500">Sin amenidades registradas.</span>@endforelse</div><div class="mt-10 rounded-3xl bg-slate-100 p-8 text-slate-500">Mapa preparado para coordenadas: {{ $property->latitude ?? 'N/D' }}, {{ $property->longitude ?? 'N/D' }}</div></div>
        <form method="post" action="{{ route('contact.requests.store') }}" class="rounded-3xl bg-[#f7f2e8] p-6">@csrf<x-alert /><input type="hidden" name="property_id" value="{{ $property->id }}"><input class="hidden" name="website" tabindex="-1" autocomplete="off"><h2 class="text-xl font-black text-[#082142]">Solicitar información</h2><label class="mt-4 grid gap-1">Nombre<input name="name" class="rounded-xl border-slate-200" required></label><label class="mt-4 grid gap-1">Teléfono<input name="phone" class="rounded-xl border-slate-200" required></label><label class="mt-4 grid gap-1">Correo<input name="email" type="email" class="rounded-xl border-slate-200"></label><label class="mt-4 grid gap-1">Mensaje<textarea name="message" class="rounded-xl border-slate-200" rows="5" required>Me interesa esta propiedad. Quiero recibir más información.</textarea></label><button class="mt-5 w-full rounded-full bg-[#082142] px-5 py-3 font-bold text-white">Enviar solicitud</button></form>
    </section>
    <section class="bg-[#f7f2e8] px-5 py-16"><div class="mx-auto max-w-7xl"><h2 class="text-3xl font-black text-[#082142]">Propiedades relacionadas</h2><div class="mt-8 grid gap-8 md:grid-cols-3">@foreach($related as $item)<x-property-card :property="$item" />@endforeach</div></div></section>
</x-public-layout>
