<x-public-layout title="Grupo Mundo Patrimonial" description="Encuentra propiedades en venta y renta con asesoría patrimonial.">
    <section class="bg-[#0d2723] text-white">
        <div class="mx-auto grid max-w-7xl gap-10 px-4 py-14 sm:px-6 lg:grid-cols-[.92fr_1.08fr] lg:items-center lg:gap-16 lg:px-8 lg:py-20">
            <div>
                <p class="text-xs font-bold uppercase tracking-[.35em] text-[#d5b673]">Real estate · inversión · patrimonio</p>
                <h1 class="mt-5 max-w-2xl font-serif text-5xl leading-[1.04] sm:text-7xl">Encuentra el<br>espacio ideal<br>para tu<br>siguiente etapa.</h1>
                <p class="mt-6 max-w-xl text-base leading-relaxed text-white/75 sm:text-lg">Descubre una selección de propiedades residenciales, comerciales e industriales para vivir, invertir y hacer crecer tu patrimonio, con asesoría profesional y acompañamiento especializado de principio a fin.</p>
                <form action="{{ route('properties.index') }}" class="mt-8 grid gap-3 rounded-2xl bg-[#f5f2eb] p-4 text-[#0d2723] shadow-2xl md:grid-cols-5 lg:-mr-24 lg:relative lg:z-10">
                    <select name="operation_type" class="rounded-lg border-[#ded8ca] bg-white"><option value="">Todas las operaciones</option><option value="sale">Venta</option><option value="rent">Renta</option><option value="presale">Preventa</option></select>
                    <select name="property_type" class="rounded-lg border-[#ded8ca] bg-white"><option value="">Tipo de propiedad</option>@foreach($propertyTypes as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select>
                    <input name="keyword" class="rounded-lg border-[#ded8ca] bg-white" placeholder="Zona o palabra clave">
                    <select name="sort" class="rounded-lg border-[#ded8ca] bg-white"><option value="recent">Más recientes</option><option value="featured">Destacadas</option></select>
                    <button class="rounded-lg bg-[#d5b673] px-5 py-3 text-sm font-bold uppercase tracking-[.12em] text-[#0d2723] transition hover:bg-[#c9a968]">Buscar propiedades</button>
                </form>
                <div class="mt-8 grid gap-4 text-sm text-white/80 sm:grid-cols-3 lg:mt-10 lg:max-w-3xl">
                    <div class="flex items-center gap-3"><span class="text-[#d5b673]" aria-hidden="true"><svg class="h-6 w-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4"><circle cx="12" cy="8" r="3"/><path d="M5.5 20c.8-3.3 2.9-5 6.5-5s5.7 1.7 6.5 5"/></svg></span><span>Asesoría personalizada</span></div>
                    <div class="flex items-center gap-3"><span class="text-[#d5b673]" aria-hidden="true"><svg class="h-6 w-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4"><path d="m4 12 5 5L20 6"/><path d="M4 20h16"/></svg></span><span>Propiedades verificadas</span></div>
                    <div class="flex items-center gap-3"><span class="text-[#d5b673]" aria-hidden="true"><svg class="h-6 w-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4"><path d="M12 3v18M3 12h18"/><circle cx="12" cy="12" r="8.5"/></svg></span><span>Acompañamiento integral</span></div>
                </div>
            </div>
            <div class="relative min-h-[390px] overflow-hidden rounded-2xl lg:min-h-[580px]">
                <img class="h-full w-full object-cover" src="https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1600&q=85" alt="Interior residencial elegante">
                <div class="absolute inset-0 bg-gradient-to-t from-[#0d2723]/40 via-transparent"></div>
            </div>
        </div>
    </section>

    <section class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24">
        <div class="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p class="text-xs font-bold uppercase tracking-[.35em] text-[#b89752]">Portafolio integral</p><h2 class="mt-4 font-serif text-5xl text-[#0d2723]">Propiedades destacadas</h2></div><div class="flex flex-wrap gap-2 text-sm"><a class="rounded-full border border-[#c9a968] px-4 py-2" href="{{ route('properties.index') }}">Todas</a><a class="rounded-full border border-[#ded8ca] px-4 py-2" href="{{ route('properties.index', ['operation_type' => 'sale']) }}">Venta</a><a class="rounded-full border border-[#ded8ca] px-4 py-2" href="{{ route('properties.index', ['operation_type' => 'rent']) }}">Renta</a><a class="rounded-full border border-[#ded8ca] px-4 py-2" href="{{ route('properties.index', ['operation_type' => 'sale_rent']) }}">Venta/Renta</a><a class="rounded-full border border-[#ded8ca] px-4 py-2" href="{{ route('properties.index', ['operation_type' => 'presale']) }}">Preventas</a><a class="rounded-full border border-[#ded8ca] px-4 py-2" href="{{ route('properties.index', ['property_type' => 'commercial']) }}">Comerciales</a></div></div>
        <div class="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-3">@forelse($featuredProperties as $property)<x-property-card :property="$property" />@empty<x-empty-state message="Pronto publicaremos nuevas propiedades destacadas." />@endforelse</div>
    </section>

    <section class="bg-[#efe9dc] py-16 lg:py-24"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><p class="text-xs font-bold uppercase tracking-[.35em] text-[#b89752]">Más que una inmobiliaria</p><h2 class="mt-4 max-w-3xl font-serif text-5xl leading-tight text-[#0d2723]">Somos aliados en la construcción de tu <em class="text-[#b89752]">patrimonio.</em></h2><div class="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-6"><x-service-card id="compra-estrategica" class="lg:col-span-2" number="01" title="Compra estratégica" text="Analizamos oportunidades inmobiliarias para ayudarte a tomar decisiones inteligentes, seguras y alineadas con tus objetivos patrimoniales." link="{{ route('services') }}#compra-estrategica" /><x-service-card id="rentas-inteligentes" class="lg:col-span-2" number="02" title="Rentas inteligentes" text="Conectamos propietarios e inquilinos ideales mediante procesos profesionales que protegen tu inversión." link="{{ route('services') }}#rentas-inteligentes" /><x-service-card id="administracion-patrimonial" class="lg:col-span-2" number="03" title="Administración patrimonial" text="Gestionamos tu propiedad para maximizar su valor, mantenerla operativa y generar tranquilidad." link="{{ route('services') }}#administracion-patrimonial" /><x-service-card id="asesoria-integral" class="lg:col-span-3" number="04" title="Asesoría integral" text="Te acompañamos en créditos, trámites inmobiliarios y estrategias para tomar mejores decisiones." link="{{ route('services') }}#asesoria-integral" /><x-service-card id="proteccion-prevencion" class="lg:col-span-3" number="05" title="Protección y prevención" text="Soluciones con seguros, pólizas jurídicas y estrategias diseñadas para cuidar tu patrimonio." link="{{ route('services') }}#proteccion-prevencion" /></div></div></section>

    <section class="bg-[#f5f2eb] py-14 lg:py-20"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><p class="text-xs font-bold uppercase tracking-[.35em] text-[#b89752]">Nuestro ecosistema patrimonial</p><div class="mt-8 grid gap-8 md:grid-cols-3"><div class="flex gap-4"><span class="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-[#0d2723] text-[#d5b673]" aria-hidden="true"><svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="m3 11 9-7 9 7v9H3v-9Z"/><path d="M8 20v-5h8v5"/></svg></span><div><h3 class="font-serif text-2xl text-[#0d2723]">Inmobiliaria</h3><p class="mt-2 text-sm leading-relaxed text-[#687773]">Compra, venta y renta de propiedades con alta potencialidad.</p></div></div><div class="flex gap-4"><span class="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-[#0d2723] text-[#d5b673]" aria-hidden="true"><svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M12 3 19 6v5c0 4.5-2.8 7.7-7 10-4.2-2.3-7-5.5-7-10V6l7-3Z"/><path d="m9 12 2 2 4-4"/></svg></span><div><h3 class="font-serif text-2xl text-[#0d2723]">Protección</h3><p class="mt-2 text-sm leading-relaxed text-[#687773]">Seguros y pólizas jurídicas para proteger lo que más te importa.</p></div></div><div class="flex gap-4"><span class="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-[#0d2723] text-[#d5b673]" aria-hidden="true"><svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M4 20V9l8-5 8 5v11"/><path d="M2 20h20M9 20v-5h6v5"/></svg></span><div><h3 class="font-serif text-2xl text-[#0d2723]">Administración</h3><p class="mt-2 text-sm leading-relaxed text-[#687773]">Cuidado, mantenimiento y crecimiento de tus activos inmobiliarios.</p></div></div></div></div></section>

    <section class="bg-[#0d2723] px-4 py-16 text-white lg:py-20"><div class="mx-auto flex max-w-5xl flex-col items-center justify-between gap-8 text-center md:flex-row md:text-left"><div class="flex items-center gap-5"><span class="grid h-16 w-16 shrink-0 place-items-center rounded-full border border-[#d5b673] text-[#d5b673]" aria-hidden="true"><svg class="h-8 w-8" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.3"><path d="m3 11 9-7 9 7v9H3v-9Z"/><path d="M8 20v-5h8v5"/></svg></span><h2 class="font-serif text-4xl leading-tight">Tu próxima propiedad puede ser una decisión.<br>Nosotros la convertimos en <em class="text-[#d5b673]">patrimonio.</em></h2></div><a class="shrink-0 rounded-full bg-[#d5b673] px-6 py-4 text-xs font-bold uppercase tracking-[.16em] text-[#0d2723] transition hover:bg-[#c9a968]" href="https://wa.me/{{ config('company.whatsapp_number') }}" target="_blank" rel="noopener">Hablar con un asesor</a></div></section>
</x-public-layout>
