<x-admin-layout :title="$property->exists ? 'Editar propiedad' : 'Crear propiedad'">
<form method="POST" enctype="multipart/form-data" action="{{ $property->exists ? route('admin.properties.update',$property) : route('admin.properties.store') }}" class="grid gap-6">@csrf @if($property->exists)@method('PUT')@endif
@php($types=['Departamento'=>'Departamento','Casa'=>'Casa','Oficina'=>'Oficina','Local'=>'Local','Terreno'=>'Terreno'])
<section class="rounded-lg bg-white p-6"><h2 class="font-serif text-2xl">Informacion general</h2><div class="mt-4 grid gap-4 md:grid-cols-2"><x-form.input label="Titulo" name="title" :value="$property->title" required/><x-form.input label="Slug" name="slug" :value="$property->slug"/><x-form.input label="Descripcion corta" name="short_description" :value="$property->short_description"/></div></section>
<section class="rounded-lg bg-white p-6"><h2 class="font-serif text-2xl">Operacion y precio</h2><div class="mt-4 grid gap-4 md:grid-cols-4"><x-form.select label="Operacion" name="operation_type" :value="$property->operation_type?->value" :options="['sale'=>'Venta','rent'=>'Renta']"/><x-form.select label="Tipo" name="property_type" :value="$property->property_type" :options="$types"/><x-form.input label="Precio" name="price" type="number" step="0.01" :value="$property->price"/><x-form.input label="Moneda" name="currency" :value="$property->currency ?: 'MXN'"/><x-form.input label="Periodo de renta" name="rent_period" :value="$property->rent_period"/></div></section>
<section class="rounded-lg bg-white p-6"><h2 class="font-serif text-2xl">Ubicacion</h2><div class="mt-4 grid gap-4 md:grid-cols-3"><x-form.input label="Calle" name="street" :value="$property->street"/><x-form.input label="Numero exterior" name="exterior_number" :value="$property->exterior_number"/><x-form.input label="Numero interior" name="interior_number" :value="$property->interior_number"/><x-form.input label="Colonia" name="neighborhood" :value="$property->neighborhood"/><x-form.input label="Ciudad" name="city" :value="$property->city"/><x-form.input label="Estado" name="state" :value="$property->state"/><x-form.input label="Codigo postal" name="postal_code" :value="$property->postal_code"/><x-form.input label="Latitud" name="latitude" :value="$property->latitude"/><x-form.input label="Longitud" name="longitude" :value="$property->longitude"/></div></section>
<section class="rounded-lg bg-white p-6"><h2 class="font-serif text-2xl">Caracteristicas</h2><div class="mt-4 grid gap-4 md:grid-cols-3"><x-form.input label="Recamaras" name="bedrooms" type="number" :value="$property->bedrooms"/><x-form.input label="Banos" name="bathrooms" type="number" step="0.5" :value="$property->bathrooms"/><x-form.input label="Estacionamientos" name="parking_spaces" type="number" :value="$property->parking_spaces"/><x-form.input label="Construccion m2" name="construction_area" type="number" step="0.01" :value="$property->construction_area"/><x-form.input label="Terreno m2" name="land_area" type="number" step="0.01" :value="$property->land_area"/><x-form.input label="Antiguedad" name="age" :value="$property->age"/></div></section>
<section class="rounded-lg bg-white p-6"><h2 class="font-serif text-2xl">Descripcion</h2><div class="mt-4"><x-form.textarea label="Descripcion completa" name="description" :value="$property->description" required/></div></section>
<section class="rounded-lg bg-white p-6"><h2 class="font-serif text-2xl">Amenidades</h2><div class="mt-4 grid gap-2 md:grid-cols-4">@foreach($amenities as $amenity)<label class="flex gap-2"><input type="checkbox" name="amenities[]" value="{{ $amenity->id }}" @checked(in_array($amenity->id, old('amenities', $property->amenities->pluck('id')->all() ?? [])))>{{ $amenity->name }}</label>@endforeach</div></section>
<section class="rounded-lg bg-white p-6"><h2 class="font-serif text-2xl">Fotografias</h2><input class="mt-4" type="file" name="images[]" multiple accept=".jpg,.jpeg,.png,.webp"><div class="mt-4 grid gap-4 md:grid-cols-4">@foreach($property->images ?? [] as $image)<div class="rounded border p-2"><img class="h-32 w-full object-cover" src="{{ Storage::url($image->path) }}" alt="{{ $image->alt_text }}"><input type="hidden" name="existing_images[{{ $image->id }}][position]" value="{{ $image->position }}"><input name="existing_images[{{ $image->id }}][alt_text]" value="{{ $image->alt_text }}" class="mt-2 w-full rounded border-[#ded8ca]" placeholder="Texto alternativo"><label class="block"><input type="radio" name="cover_image_id" value="{{ $image->id }}" @checked($image->is_cover)> Portada</label><label class="block text-red-700"><input type="checkbox" name="delete_images[]" value="{{ $image->id }}"> Eliminar</label></div>@endforeach</div></section>
<section class="rounded-lg bg-white p-6"><h2 class="font-serif text-2xl">Publicacion</h2><p class="mt-2 text-sm text-[#687773]">Solo las propiedades con estado Publicada se muestran en el sitio publico.</p><div class="mt-4 grid gap-4 md:grid-cols-3"><x-form.select label="Estado" name="status" :value="$property->status?->value" :options="['published'=>'Publicada','draft'=>'Borrador','sold'=>'Vendida','rented'=>'Rentada','archived'=>'Archivada']"/><x-form.input label="Fecha de publicacion" name="published_at" type="datetime-local" :value="$property->published_at?->format('Y-m-d\TH:i')"/><label class="mt-7 flex gap-2"><input type="checkbox" name="is_featured" value="1" @checked(old('is_featured',$property->is_featured))> Destacada</label></div></section>
<button class="rounded bg-[#0d2723] px-6 py-3 font-bold text-white">Guardar propiedad</button></form>
</x-admin-layout>
